import os

# DATABASE CONFIG
DATABASE_USER = 'root'
DATABASE_PASSWORD = 'password123'
DATABASE_HOST = 'jmoney_db:3306'
DATABASE_NAME = 'jmoney'
SQLALCHEMY_DATABASE_URI = f"mysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False
